### ISSUE TITLE
Tag codes for NER

### ISSUE THREAD

**Issue by remintz** [HAILab-PUCPR/BioBERTpt#1]
Hi,

I'm trying to use this model on a Named Entity Recognition test. What tags may I expect and what are their codes?

Thanks

Renato

**Comment by lisaterumi** [comment]
Hello Renato,

BioBERTpt is a language model fine-tuned for clinical and biomedical texts in Portuguese, in the same way as BioBERT for English.

In order to use it in a NER task, it would be necessary to fine-tune the model for the NER task.

We already did it, to compare our models performance, soon we can make available these models trained for NER.

But for now, you could fine-tune the model for example with [this corpus](https://github.com/fabioacl/PortugueseClinicalNER).

A very easy way is using the [Hugging Faces library](https://github.com/huggingface/transformers/tree/master/examples/token-classification):

python run_ner.py \
  --path_of_biobertpt \
  --dataset_name data_downloaded \
  --output_dir /test-ner \
  --do_train \
  --do_eval

Hope this helps.

Regards

**Comment by lisaterumi** [comment]
Hello Renato,

We published the model for NER task, fine-tuned with [PortugueseClinicalNER](https://github.com/fabioacl/PortugueseClinicalNER), as well as a [notebook](https://github.com/HAILab-PUCPR/BioBERTpt/blob/master/ner_prediction.ipynb) with instructions on how to use it.

Hope this helps!

Regards, Elisa

**Comment by remintz** [comment]
Hi Elisa, I still have a question regarding the Tags. The notebook makes reference to the following tags:

```
#Reference: 
#CH: Characterization; 
#T: Test; 
#EV: Evolution; 
#G: Genetics; 
#AS: Anatomical Site; 
#N: Negation; 
#OBS: Additional Observations; 
#C: Condition; 
#R: Results; 
#DT: DateTime; 
#THER: Therapeutics; 
#V: Value; 
#RA: Route of Administration; 
#O: Out
```

The README.md file and [paper you've published](https://www.aclweb.org/anthology/2020.clinicalnlp-1.7.pdf) say:

> We evaluate our models on SemClinBr, a semantically annotated corpus for Portuguese clinical NER, containing 1,000 labeled clinical notes. These corpus comprehended 100 UMLS semantic types, summarized in 13 groups of entities: Disorders, Chemicals and Drugs, Medical Procedure, Diagnostic Procedure, Disease Or Syndrome, Findings, Health Care Activity, Laboratory or Test Result, Medical Device, Pharmacologic Substance, Quantitative Concept, Sign or Symptom and Therapeutic or Preventive Procedure.

Is there any mapping between the referenced tags and the 13 UMLS entity groups? Is this model you've published here able to identify the 13 UMLS entity groups? How can we do that?

Thanks

**Comment by lisaterumi** [comment]
Hi Renato,

In our paper, the mapping with the UMLS was done with the [SemClinBr corpus](https://github.com/HAILab-PUCPR/SemClinBr).

At the moment, we publish the NER with another corpus ([Portuguese Clinical NER](https://github.com/fabioacl/PortugueseClinicalNER)) which has no mapping with UMLS, as we are still waiting for the ethics committee to be able to publish with SemClinBr.

Regards, Elisa

**Comment by lisaterumi** [comment]
@remintz we made all our NER models available in Hugging faces, now with integration with UMLS (trained on SemclinBr).

As semclinbr is a multi-token (multi-label) corpus, we created a NER model for extracting each entity separately. The models are:

https://huggingface.co/pucpr/clininalnerpt-healthcare
https://huggingface.co/pucpr/clininalnerpt-chemical
https://huggingface.co/pucpr/clininalnerpt-diagnostic
https://huggingface.co/pucpr/clininalnerpt-therapeutic
https://huggingface.co/pucpr/clininalnerpt-sign
https://huggingface.co/pucpr/clininalnerpt-quantitative
https://huggingface.co/pucpr/clininalnerpt-procedures
https://huggingface.co/pucpr/clininalnerpt-pharmacologic
https://huggingface.co/pucpr/clininalnerpt-medical
https://huggingface.co/pucpr/clininalnerpt-laboratory
https://huggingface.co/pucpr/clininalnerpt-healthcare
https://huggingface.co/pucpr/clininalnerpt-finding
https://huggingface.co/pucpr/clininalnerpt-disorders
https://huggingface.co/pucpr/clininalnerpt-disease

On the Huggingfaces page you have examples of how to use them, but I am also available in case of doubt.

Regards.

**Comment by lisaterumi** [comment]
For more examples of how to use our models in HuggingFaces, please see: https://github.com/HAILab-PUCPR/ENTClinPT
